/* ══════════════════════════════════════════════
   WAR ROOM — LIVE PIPELINE
   Agent definitions, live state, SSE helpers,
   callAgent, runPipeline, scheduleSide.
   ══════════════════════════════════════════════ */

require('dotenv').config();
const path = require('path');
const fs = require('fs');
const vm = require('vm');

// Sucrase: real TypeScript → JavaScript transpiler (permanent TS fix)
let sucraseTransform = null;
try { sucraseTransform = require('sucrase').transform; } catch { /* optional dep */ }

/* ── Auto-close truncated JS ──
   When the builder hits a token limit mid-IIFE, the file ends without closing
   braces/parens. Try progressively more closing tokens until vm.Script passes. */
function autoCloseJS(code) {
  if (!code || !code.trim()) return code;
  const attempts = [
    '', '\n}', '\n}\n}', '\n}\n}\n}', '\n}\n}\n}\n}',
    '\n})();', '\n}\n})();', '\n}\n}\n})();', '\n}\n}\n}\n})();',
    '\n  }\n})();', '\n    }\n  }\n})();',
  ];
  for (const closer of attempts) {
    try { new (require('vm').Script)(code + closer); return code + closer; } catch {}
  }
  return code; // return unchanged if nothing works
}
const { buildPrompt } = require('./prompts');
const { createMessage, getModels } = require('./llm');
const { validateJS, retryBuilderFile } = require('./tools/validator');
const { resolveCDNs } = require('./tools/cdnResolver');
const { webSearch, buildSearchQuery } = require('./tools/search');

const sleep = ms => new Promise(r => setTimeout(r, ms));

/* ── Agent logger ── */
function writeAgentLog(agentId, cycle, promptText, rawResponse, inputTokens, outputTokens) {
  if (!live.workspaceDir) return;
  try {
    const logDir = path.join(live.workspaceDir, 'logs');
    fs.mkdirSync(logDir, { recursive: true });
    const logFile = path.join(logDir, 'session.log');
    const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
    const divider = '═'.repeat(60);
    const entry = [
      `\n${divider}`,
      `CYCLE ${cycle} | ${(LIVE_AGENTS[agentId]?.name || agentId).toUpperCase()} | ${ts}`,
      `TOKENS: ${inputTokens} in / ${outputTokens} out`,
      divider,
      '── PROMPT ──',
      promptText,
      '',
      '── RESPONSE ──',
      rawResponse,
      '',
    ].join('\n');
    fs.appendFileSync(logFile, entry, 'utf8');
  } catch { /* logging is non-critical */ }
}

/* ── Agent definitions ── */
const LIVE_AGENTS = {
  ceo: {
    name: 'CEO', abbr: 'CEO', role: 'Chief Executive',
    color: '#00e676', maxTokens: 800,
    communicatesWith: ['lead-eng'],
  },
  'lead-eng': {
    name: 'Lead Engineer', abbr: 'LE', role: 'Lead Engineer',
    color: '#4fc3f7', maxTokens: 2000,
    communicatesWith: ['builder'],
  },
  designer: {
    name: 'UI Designer', abbr: 'UID', role: 'UI Designer',
    color: '#ce93d8', maxTokens: 800,
    communicatesWith: ['builder'],
  },
  builder: {
    name: 'Developer', abbr: 'DEV', role: 'Full-Stack Developer',
    color: '#ffb74d', maxTokens: 4000,
    communicatesWith: [],
  },
  qa: {
    name: 'QA Engineer', abbr: 'QA', role: 'QA Engineer',
    color: '#80cbc4', maxTokens: 400,
    communicatesWith: ['lead-eng'],
  },
  sales: {
    name: 'Sales Lead', abbr: 'SL', role: 'Sales Lead',
    color: '#f06292', maxTokens: 600,
    communicatesWith: ['ceo'],
  },
};

/* ── Live state ── */
let live = {
  running: false,
  paused: false,
  speed: 1,
  brief: '',
  sessionId: null,
  workspaceDir: null,
  contexts: {},
  timers: {},
  tokens: 0,
  startTime: null,
  clients: [],
  files: [],
  salesV: 1,
  msgCount: 0,
  pastPriorities: [],
  featurePriority: '',
};

/* ── SSE helpers ── */
function emit(event, data) {
  const chunk = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
  live.clients = live.clients.filter(c => {
    try { c.write(chunk); return true; } catch { return false; }
  });
}

function pushContext(agentId, fromLabel, text) {
  if (!live.contexts[agentId]) live.contexts[agentId] = [];
  live.contexts[agentId].push(`${fromLabel}: ${text}`);
  if (live.contexts[agentId].length > 6) live.contexts[agentId].shift();
}

function pushMsg(msg) {
  live.msgCount++;
  emit('new-message', { ...msg, id: live.msgCount, timestamp: Date.now() });
}

function stopAll() {
  Object.values(live.timers).forEach(t => clearTimeout(t));
  live.timers = {};
}

/* ── Post-build validator: auto-generate any missing required files ── */
async function ensureRequiredFiles() {
  if (!live.running || !live.workspaceDir) return;

  // Always require index.html, style.css, app.js. data.js is generated by builder — not auto-patched.
  const required = ['public/index.html', 'public/style.css', 'public/app.js'];
  const missing = required.filter(p => !live.files.find(f => f.path === p));
  if (!missing.length) return;

  const provider  = live.provider || 'anthropic';
  const apiKey    = live.apiKey   || process.env.ANTHROPIC_API_KEY;
  const model     = getModels(provider).smart;

  // Give the LLM context of what was already built
  const builtCtx = live.files
    .filter(f => f.path.startsWith('public/'))
    .map(f => `=== ${f.path} (${f.lines} lines) ===\n${(f.content || '').slice(0, 600)}`)
    .join('\n\n') || '(no files built yet)';

  for (const filename of missing) {
    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚠️ ${filename} missing after builder — auto-generating...` });

    const hasDataJs = live.files.some(f => f.path === 'public/data.js');
    const designSpec = (() => { try { return fs.readFileSync(path.join(live.workspaceDir, 'docs/design-spec.md'), 'utf8').slice(0, 800); } catch { return ''; } })();
    const hint = filename.endsWith('.html')
      ? `Complete HTML page. Must include <link rel="stylesheet" href="style.css">${hasDataJs ? ', <script src="data.js"></script>' : ''} and <script src="app.js"></script>. Use element IDs that match the JavaScript above.`
      : filename.endsWith('.css')
      ? `Complete production stylesheet. Extract every element ID and class from the index.html above and style ALL of them. Use CSS custom properties (--variables) for colors. Dark theme. Make it look polished — proper spacing, card shadows, typography, color-coded values, smooth transitions. ${designSpec ? `\nDESIGN SPEC:\n${designSpec}` : ''}`
      : `Complete JavaScript. Target the element IDs in index.html above.${hasDataJs ? ' State and simulation already live in data.js — app.js handles DOM updates, rendering, and events only.' : ' Implement all interactive features from the project brief.'} No stubs.`;

    const prompt = `You are a developer fixing an incomplete build.

PROJECT: ${live.brief}
FEATURE: ${live.featurePriority || 'build complete app'}

FILES ALREADY BUILT:
${builtCtx}

The file "${filename}" was NOT generated. You MUST output it now.
${hint}

Respond in this EXACT format only — no other text:
TYPE: work
FILENAME: ${filename}
TASK: generate missing file
---
[complete file content here]`;

    try {
      const { text: raw, inputTokens, outputTokens } = await createMessage({
        provider, apiKey, model, maxTokens: 6000,
        messages: [{ role: 'user', content: prompt }],
      });
      live.tokens += inputTokens + outputTokens;
      emit('token-update', { total: live.tokens, delta: inputTokens + outputTokens });

      const sepM = raw.match(/\n-{3,}\r?\n/);
      const filecontent = sepM ? raw.slice(raw.indexOf(sepM[0]) + sepM[0].length).trim() : raw.trim();
      if (!filecontent) continue;

      // CDN resolve if HTML
      const content = filename.endsWith('.html') ? resolveCDNs(filecontent) : filecontent;
      const safePath = filename;
      const fullPath = path.join(live.workspaceDir, safePath);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf8');
      const lines = content.split('\n').length;
      const entry = { path: safePath, content, agentId: 'builder', ts: Date.now(), lines };
      const idx = live.files.findIndex(f => f.path === safePath);
      if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
      emit('new-file', entry);
      emit('preview-refresh', { path: safePath, ts: Date.now() });
      pushMsg({ from: 'builder', to: null, type: 'file',
        message: `📄 \`${safePath}\` — ${lines} lines · auto-generated (was missing)` });
    } catch (err) {
      pushMsg({ from: 'system', to: null, type: 'system',
        message: `⚠️ Could not generate ${filename}: ${err.message.slice(0, 80)}` });
    }
  }
}

/* ── CSS Specialist: dedicated call that generates perfect CSS from the actual HTML ──
   Called after every cycle 1 builder run. Reads the HTML already on disk, extracts
   every ID/class, and writes a COMPLETE stylesheet targeting exactly those selectors.
   This is separate from ensureCSSCoverage (which patches when coverage < 60%) — this
   one runs unconditionally on cycle 1 to guarantee CSS quality from the start.        */
async function runCSSSpecialist() {
  if (!live.running || !live.workspaceDir) return;

  const htmlPath = path.join(live.workspaceDir, 'public/index.html');
  if (!fs.existsSync(htmlPath)) return;

  const html = fs.readFileSync(htmlPath, 'utf8');
  const cleanHtml = html.replace(/<script[\s\S]*?<\/script>/gi, '').replace(/<style[\s\S]*?<\/style>/gi, '');

  // Extract all unique IDs and classes
  const ids      = [...new Set([...cleanHtml.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]))];
  const classes  = [...new Set([...cleanHtml.matchAll(/\bclass="([^"]+)"/g)].flatMap(m => m[1].split(/\s+/)).filter(Boolean))];
  if (!ids.length && !classes.length) return;

  const designSpec = (() => { try { return fs.readFileSync(path.join(live.workspaceDir, 'docs/design-spec.md'), 'utf8').slice(0, 1200); } catch { return ''; } })();

  pushMsg({ from: 'system', to: null, type: 'system',
    message: `🎨 CSS Specialist running — writing complete stylesheet for ${ids.length} IDs + ${classes.length} classes...` });

  const provider = live.provider || 'anthropic';
  const apiKey   = live.apiKey   || process.env.ANTHROPIC_API_KEY;
  const model    = getModels(provider).smart;

  const prompt = `You are an expert CSS engineer. Write a COMPLETE, production-quality stylesheet for this exact HTML page.

PROJECT: ${live.brief}

${designSpec ? `DESIGN SPEC:\n${designSpec}\n` : ''}

FULL HTML (read every element ID and class from here):
${html}

ELEMENT IDs present in the HTML: ${ids.join(', ')}
CSS CLASSES present in the HTML: ${classes.join(', ')}

REQUIREMENTS — every single one is mandatory:
1. Declare :root CSS custom properties (--bg, --surface, --accent, --text, --border, etc.)
2. Style EVERY element ID listed above — none can be missing
3. Style EVERY CSS class listed above — none can be missing
4. Dark theme with rich visual hierarchy: gradients, card shadows, subtle glows
5. Full layout: header fixed/sticky, hero section with grid, content sections with flex/grid
6. Typography scale: headings, body, labels, captions all differentiated
7. Interactive states: :hover, :active, :focus — all buttons and links
8. Smooth transitions (0.2s ease) on all interactive elements
9. Mobile responsive: @media (max-width: 768px) breakpoints for all major sections
10. Animations: at least fade-in on load, pulse on CTAs

Output ONLY plain CSS. No markdown code fences. No explanations. Start directly with :root {`;

  try {
    const { text, inputTokens, outputTokens } = await createMessage({
      provider, apiKey, model, maxTokens: 10000,
      messages: [{ role: 'user', content: prompt }],
    });
    live.tokens += inputTokens + outputTokens;
    emit('token-update', { total: live.tokens, delta: inputTokens + outputTokens });

    let css = text.trim().replace(/^```[^\n]*\n?/, '').replace(/\n?```$/, '');
    if (!css || css.length < 200) return;

    const cssPath = path.join(live.workspaceDir, 'public/style.css');
    fs.writeFileSync(cssPath, css, 'utf8');

    const entry = { path: 'public/style.css', content: css, agentId: 'css-specialist', ts: Date.now(), lines: css.split('\n').length };
    const idx = live.files.findIndex(f => f.path === 'public/style.css');
    if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
    emit('new-file', entry);
    emit('preview-refresh', { path: 'public/style.css', ts: Date.now() });

    pushMsg({ from: 'system', to: null, type: 'system',
      message: `✅ CSS Specialist complete — ${css.split('\n').length} lines, all ${ids.length + classes.length} selectors covered` });
  } catch (err) {
    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚠️ CSS Specialist failed: ${err.message.slice(0, 80)}` });
  }
}

/* ── Post-build CSS coverage validator ── */
// After every cycle, extract all IDs and classes from index.html and check
// that style.css has rules for them. If major selectors are uncovered, patch
// style.css automatically with a targeted LLM call.
async function ensureCSSCoverage() {
  if (!live.running || !live.workspaceDir) return;

  const htmlPath = path.join(live.workspaceDir, 'public/index.html');
  const cssPath  = path.join(live.workspaceDir, 'public/style.css');
  if (!fs.existsSync(htmlPath) || !fs.existsSync(cssPath)) return;

  const html = fs.readFileSync(htmlPath, 'utf8');
  const css  = fs.readFileSync(cssPath,  'utf8');

  // Extract every id="..." and class="..." from HTML (skip <script> and <style> blocks)
  const cleanHtml = html.replace(/<script[\s\S]*?<\/script>/gi, '').replace(/<style[\s\S]*?<\/style>/gi, '');
  const ids      = [...cleanHtml.matchAll(/\bid="([^"]+)"/g)].map(m => '#' + m[1].trim());
  const classes  = [...cleanHtml.matchAll(/\bclass="([^"]+)"/g)]
    .flatMap(m => m[1].trim().split(/\s+/))
    .filter(Boolean)
    .map(c => '.' + c);

  const allSelectors = [...new Set([...ids, ...classes])];
  if (!allSelectors.length) return;

  // A selector is "covered" if it literally appears in the CSS (e.g. #header, .feature-card)
  const uncovered = allSelectors.filter(sel => !css.includes(sel));

  const coveragePct = Math.round(((allSelectors.length - uncovered.length) / allSelectors.length) * 100);

  // Only patch if coverage is below 60%
  if (coveragePct >= 60) return;

  pushMsg({ from: 'system', to: null, type: 'system',
    message: `⚠️ CSS coverage ${coveragePct}% (${uncovered.length}/${allSelectors.length} selectors missing) — auto-patching...` });

  const provider = live.provider || 'anthropic';
  const apiKey   = live.apiKey   || process.env.ANTHROPIC_API_KEY;
  const model    = getModels(provider).smart;

  const prompt = `You are a CSS expert. The following HTML page has selectors with NO CSS rules yet.
Write CSS ONLY for the missing selectors listed below — do not repeat rules that already exist.

HTML (for structure context):
${html.slice(0, 4000)}

EXISTING CSS THEME (match this color scheme / style exactly):
${css.slice(0, 800)}

SELECTORS THAT ARE MISSING CSS RULES (write rules for ALL of them):
${uncovered.join('\n')}

Rules:
- Output PLAIN CSS only — no markdown fences, no explanations, no comments except /* section labels */
- Match the existing dark theme and color variables
- Every selector must have at least display, color, and spacing rules
- Make the page look polished and production-ready`;

  try {
    const { text, inputTokens, outputTokens } = await createMessage({
      provider, apiKey, model, maxTokens: 4000,
      messages: [{ role: 'user', content: prompt }],
    });
    live.tokens += inputTokens + outputTokens;
    emit('token-update', { total: live.tokens, delta: inputTokens + outputTokens });

    const patch = text.trim().replace(/^```[^\n]*\n?/, '').replace(/\n?```$/, '');
    if (!patch) return;

    fs.appendFileSync(cssPath, '\n\n/* ═══ AUTO-PATCHED MISSING SELECTORS ═══ */\n' + patch, 'utf8');

    // Update live.files entry
    const newCss = fs.readFileSync(cssPath, 'utf8');
    const entry = { path: 'public/style.css', content: newCss, agentId: 'system', ts: Date.now(), lines: newCss.split('\n').length };
    const idx = live.files.findIndex(f => f.path === 'public/style.css');
    if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
    emit('new-file', entry);
    emit('preview-refresh', { path: 'public/style.css', ts: Date.now() });

    pushMsg({ from: 'system', to: null, type: 'system',
      message: `✅ CSS coverage patched — ${uncovered.length} selectors added to style.css (now ~${Math.min(100, coveragePct + Math.round(uncovered.length / allSelectors.length * 100))}% covered)` });
  } catch (err) {
    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚠️ CSS patch failed: ${err.message.slice(0, 80)}` });
  }
}

/* ── Cycle-start JS healer ──
   Before each cycle, validate existing JS files on disk. If any are invalid
   (truncated from a prior failed cycle), auto-close or LLM-repair them before
   the builder tries to append new code. Appending to a broken file = broken file. */
async function ensureValidJS() {
  if (!live.running || !live.workspaceDir) return;
  for (const rel of ['public/app.js', 'public/data.js']) {
    const fullPath = path.join(live.workspaceDir, rel);
    if (!fs.existsSync(fullPath)) continue;
    const code = fs.readFileSync(fullPath, 'utf8');
    const { valid, error } = validateJS(code);
    if (valid) continue;

    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚠️ ${rel} invalid on disk (${error.slice(0, 60)}) — healing before cycle starts...` });

    // Fast path: try auto-closing unclosed braces
    const healed = autoCloseJS(code);
    if (validateJS(healed).valid) {
      fs.writeFileSync(fullPath, healed, 'utf8');
      const idx = live.files.findIndex(f => f.path === rel);
      const entry = { path: rel, content: healed, agentId: 'system', ts: Date.now(), lines: healed.split('\n').length };
      if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
      pushMsg({ from: 'system', to: null, type: 'system', message: `🩹 ${rel}: auto-closed and healed` });
      continue;
    }

    // Slow path: LLM repair
    try {
      const provider = live.provider || 'anthropic';
      const apiKey   = live.apiKey   || process.env.ANTHROPIC_API_KEY;
      const fixed = await retryBuilderFile({
        provider, apiKey, model: getModels(provider).smart,
        brokenCode: code, error, filename: rel, context: live.brief,
      });
      if (fixed && validateJS(fixed).valid) {
        fs.writeFileSync(fullPath, fixed, 'utf8');
        const idx = live.files.findIndex(f => f.path === rel);
        const entry = { path: rel, content: fixed, agentId: 'system', ts: Date.now(), lines: fixed.split('\n').length };
        if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
        emit('new-file', entry);
        pushMsg({ from: 'system', to: null, type: 'system', message: `✅ ${rel}: LLM-healed — now valid` });
      }
    } catch { /* healer is best-effort */ }
  }
}

/* ── Feature inventory — written after each builder run ──
   Extracts function names and state keys from the built JS files and saves
   them to docs/features.json. The builder reads this on cycle 2+ to know
   what it must preserve when it rewrites app.js / data.js from scratch. */
function updateFeaturesJson() {
  if (!live.running || !live.workspaceDir) return;
  try {
    const read = p => { try { return fs.readFileSync(path.join(live.workspaceDir, p), 'utf8'); } catch { return ''; } };
    const dataJs = read('public/data.js');
    const appJs  = read('public/app.js');
    const allJs  = dataJs + '\n' + appJs;

    const functions = [...new Set(
      [...allJs.matchAll(/^(?:function\s+(\w+)|(?:const|let|var)\s+(\w+)\s*=\s*(?:function|\([^)]*\)\s*=>))/gm)]
        .map(m => m[1] || m[2]).filter(Boolean)
    )].slice(0, 40);

    const stateMatch = allJs.match(/const\s+state\s*=\s*\{([^}]*)\}/s);
    const stateKeys = stateMatch
      ? [...new Set([...stateMatch[1].matchAll(/(\w+)\s*:/g)].map(m => m[1]))].slice(0, 20)
      : [];

    const featPath = path.join(live.workspaceDir, 'docs/features.json');
    fs.writeFileSync(featPath, JSON.stringify({ cycle: live.cycle || 0, functions, stateKeys }, null, 2), 'utf8');
  } catch { /* non-critical */ }
}

/* ── Core agent call (returns promise) ── */
function isConnectionError(err) {
  const msg = (err.message || '').toLowerCase();
  return msg.includes('connection') || msg.includes('network') || msg.includes('econnreset')
    || msg.includes('socket') || msg.includes('timeout') || msg.includes('enotfound')
    || err.constructor?.name === 'APIConnectionError' || err.constructor?.name === 'APIConnectionTimeoutError';
}

async function callAgent(agentId, _retries = 0) {
  if (!live.running || live.paused) return;
  const agent = LIVE_AGENTS[agentId];
  emit('agent-status', { agentId, status: 'thinking' });

  try {
    // CEO and Lead Engineer use the smart model — their decisions/specs drive everything downstream
    const usesSmart = ['builder', 'ceo', 'lead-eng'].includes(agentId);
    const provider = live.provider || 'anthropic';
    const apiKey   = live.apiKey   || process.env.ANTHROPIC_API_KEY;
    const models   = getModels(provider);
    const model    = usesSmart ? models.smart : models.fast;
    // Builder gets more tokens in FIX mode and on cycle 1 (complete app build)
    const isFix    = agentId === 'builder' && (live.featurePriority || '').trim().startsWith('FIX:');
    const maxTokens = agentId === 'builder'
      ? (isFix ? 16000 : (live.cycle === 1 ? 16000 : 10000))
      : agent.maxTokens;

    // Tool 3: Web search for CEO and lead-eng before building prompt
    let searchResults = '';
    if (['ceo', 'lead-eng'].includes(agentId) && (live.searchApiKey || process.env.SERPER_API_KEY)) {
      const query = buildSearchQuery(agentId, live);
      if (query) searchResults = await webSearch(query, live.searchApiKey);
    }

    const promptText = await buildPrompt(agentId, live, searchResults);

    // Tool 4: Vision analysis — CEO gets a structured site health report before making decisions
    let visionNote = '';
    if (agentId === 'ceo' && live.previewScreenshot) {
      try {
        const prevReport = live.lastVisionReport ? `\nPREVIOUS CYCLE REPORT: ${live.lastVisionReport.slice(0, 200)}` : '';
        const { text: visionText, inputTokens: vi, outputTokens: vo } = await createMessage({
          provider, apiKey,
          model: models.smart,   // smart model — needs to understand what it's seeing
          maxTokens: 700,
          messages: [{
            role: 'user',
            content: [
              { type: 'image', source: { type: 'base64', media_type: live.previewScreenshot.mediaType, data: live.previewScreenshot.base64 } },
              { type: 'text', text: `You are reviewing a screenshot of a web app being built. The project brief is: "${(live.brief || '').slice(0, 150)}"
${prevReport}

Answer each question precisely:
1. SITE STATE: BROKEN or WORKING (broken = blank/spinner/error/placeholder; working = real content visible)
2. HEALTH SCORE: 1–10 (1=blank/broken, 10=polished and complete)
3. WHAT IS VISIBLE RIGHT NOW: List every distinct UI element you can actually see (panels, charts, cards, buttons, text, colors)
4. WHAT IS MISSING or BROKEN: Compare what you see against the project brief — what key features should be visible but aren't?
5. REGRESSION: Compared to the previous cycle report above, did things improve, stay the same, or get worse?
One sentence per point. Be brutally specific — not "content area empty" but "the chart canvas is black, no price data rendered, no coin cards in the top bar".` },
            ],
          }],
        });
        live.tokens += vi + vo;
        emit('token-update', { total: live.tokens, delta: vi + vo });
        live.lastVisionReport = visionText;
        visionNote = `👁 VISION REPORT (what the site looks like RIGHT NOW):\n${visionText}\n\n`;
        // Emit to feed so user sees what the CEO sees
        pushMsg({ from: 'ceo', to: null, type: 'communicate',
          message: `👁 Site check — ${visionText.slice(0, 400)}` });
      } catch { /* vision analysis is optional, skip on error */ }
    }

    // CEO gets the screenshot embedded in vision pre-analysis above — no need to send it again.
    // Builder gets the screenshot directly so it can see what to fix.
    const useScreenshot = agentId === 'builder';
    const fullPrompt = visionNote + promptText;
    const userContent = (useScreenshot && live.previewScreenshot)
      ? [
          { type: 'image', source: { type: 'base64', media_type: live.previewScreenshot.mediaType, data: live.previewScreenshot.base64 } },
          { type: 'text', text: `This is a screenshot of the current website state.\n\n${fullPrompt}` },
        ]
      : fullPrompt;

    let { text: raw, inputTokens, outputTokens } = await createMessage({
      provider, apiKey, model,
      maxTokens,
      messages: [{ role: 'user', content: userContent }],
    });

    // Truncation detection: if output hit the exact limit, the response was cut off — continue it
    if (agentId === 'builder' && outputTokens >= maxTokens - 10) {
      pushMsg({ from: 'system', to: null, type: 'system',
        message: `⚠️ DEVELOPER output truncated at ${outputTokens} tokens — continuing...` });
      try {
        const { text: cont, inputTokens: ci, outputTokens: co } = await createMessage({
          provider, apiKey, model,
          maxTokens: 6000,
          messages: [
            { role: 'user', content: userContent },
            { role: 'assistant', content: raw },
            { role: 'user', content: 'The previous response was cut off mid-file. Continue writing EXACTLY from where it stopped. Do not repeat any code already written. Do not add any explanation.' },
          ],
        });
        raw = raw + cont;
        inputTokens += ci; outputTokens = co;
        pushMsg({ from: 'system', to: null, type: 'system', message: `✅ Continuation 1 received — ${co} additional tokens` });
        // If first continuation also hit its limit, do one more pass (cycle 1 complex apps can need ~24k tokens)
        if (co >= 6000 - 10) {
          try {
            const { text: cont2, inputTokens: ci2, outputTokens: co2 } = await createMessage({
              provider, apiKey, model,
              maxTokens: 6000,
              messages: [
                { role: 'user', content: userContent },
                { role: 'assistant', content: raw },
                { role: 'user', content: 'Still not finished. Continue writing EXACTLY from where it stopped. Do not repeat any code. Do not add explanations.' },
              ],
            });
            raw = raw + cont2;
            inputTokens += ci2; outputTokens += co2;
            pushMsg({ from: 'system', to: null, type: 'system', message: `✅ Continuation 2 received — ${co2} additional tokens` });
          } catch { /* second continuation is best-effort */ }
        }
      } catch { /* continuation is best-effort */ }
    }

    live.tokens += inputTokens + outputTokens;
    emit('token-update', { total: live.tokens, delta: inputTokens + outputTokens });
    writeAgentLog(agentId, live.cycle || 0, fullPrompt, raw, inputTokens, outputTokens);

    // Parse multiple FILE blocks separated by ===FILE===
    const fileBlocks = raw.split(/\n?={3,}FILE={3,}\n?/i);
    let didWork = false;

    for (const block of fileBlocks) {
      const typeM = block.match(/^TYPE\s*:\s*(\w+)/im);
      const type  = typeM?.[1]?.toLowerCase();
      if (type === 'work') {
        const filename    = block.match(/^FILENAME\s*:\s*(.+)/im)?.[1]?.trim();
        const task        = block.match(/^TASK\s*:\s*(.+)/im)?.[1]?.trim() || '';
        const sepM        = block.match(/\n-{3,}\r?\n/);
        let filecontent = sepM ? block.slice(block.indexOf(sepM[0]) + sepM[0].length).trim() : '';
        if (!filename || !filecontent) continue;

        // Skip trivially empty JS/CSS blocks
        if (filename.endsWith('.js') || filename.endsWith('.css')) {
          const meaningful = filecontent.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/[\s;]/g, '');
          if (!meaningful) continue;
        }

        // Strip TypeScript syntax from JS/HTML files before validation.
        // Primary: sucrase (real transpiler). Fallback: regex stripper.
        function stripTS(code) {
          if (sucraseTransform) {
            try {
              return sucraseTransform(code, { transforms: ['typescript'] }).code;
            } catch { /* fall through to regex */ }
          }
          return code
            // Remove multi-line interface declarations
            .replace(/\binterface\s+\w[\w\s,<>]*\{[^{}]*\}/g, '')
            // Remove type alias lines
            .replace(/^\s*type\s+\w[\w<>, ]*\s*=.+;?\s*$/gm, '')
            // Remove import/export type lines
            .replace(/^(?:import|export)\s+type\b.+$/gm, '')
            // Remove 'as SomeType' casts
            .replace(/\s+as\s+(?:[A-Z]\w*|string|number|boolean|any|never|void)(?:<[^>]*>)?(?:\[\])?\b/g, '')
            // Remove return type annotations: ): Type {  ): Type =>  ): Type;
            .replace(/\)\s*:\s*(?:[A-Z]\w*|string|number|boolean|any|void|never|null|undefined)(?:<[^>]*>)?(?:\[\])?\s*(?=[{;(]|=>|\s*\n)/g, ') ')
            // Remove standalone class field declarations: "  fieldName: Type;" or "  fieldName: Type\n"
            .replace(/^(\s*)(\w+)\??\s*:\s*(?:[A-Z]\w*|string|number|boolean|any|void|never|null|undefined)(?:<[^>]*>)?(?:\[\])?(\s*[;,]?\s*$)/gm, '')
            // Remove parameter/variable type annotations: name: Type followed by , ) ; = { or end of line
            .replace(/(\w+)\??\s*:\s*(?:[A-Z]\w*|string|number|boolean|any|void|never|null|undefined)(?:<[^>]*>)?(?:\[\])?\s*(?=[,);={;]|\s*\n)/g, '$1')
            // Remove generic type params on function/arrow declarations
            .replace(/(\bfunction\s+\w+)<[\w\s,extends]+>(\s*\()/g, '$1$2')
            .replace(/(<[\w\s,extends]+>)(\s*\([^)]*\)\s*(?::\s*\w+\s*)?=>)/g, '$2')
            // Remove readonly, abstract, declare
            .replace(/\b(?:readonly|abstract|declare)\s+/g, '')
            // Remove access modifiers
            .replace(/\b(?:public|private|protected)\s+(?=\w)/g, '');
        }

        if (filename.endsWith('.js')) {
          filecontent = stripTS(filecontent);
        }
        // Also strip TypeScript from inline <script> blocks in HTML
        if (filename.endsWith('.html')) {
          filecontent = filecontent.replace(
            /(<script(?:\s[^>]*)?>)([\s\S]*?)(<\/script>)/gi,
            (_, open, code, close) => open + stripTS(code) + close
          );
        }

        // Tool 1: JS Syntax Validator — validate and auto-retry on syntax error
        if (agentId === 'builder' && filename.endsWith('.js')) {
          const { valid, error } = validateJS(filecontent);
          if (!valid) {
            pushMsg({ from: 'system', to: null, type: 'system',
              message: `🔧 SYNTAX ERROR in ${filename} — auto-fixing: ${error.slice(0, 80)}` });
            const fixed = await retryBuilderFile({
              provider, apiKey, model,
              brokenCode: filecontent,
              error,
              filename,
              context: live.featurePriority || live.brief,
            });
            if (fixed) {
              const { valid: fixedValid } = validateJS(fixed);
              if (fixedValid) {
                filecontent = fixed;
                pushMsg({ from: 'system', to: null, type: 'system', message: `✅ SYNTAX FIXED — ${filename} rewritten successfully` });
              } else {
                pushMsg({ from: 'system', to: null, type: 'system', message: `⚠️ Could not fix syntax — skipping ${filename}` });
                continue;
              }
            } else {
              continue;
            }
          }
        }

        // Tool 2: CDN Resolver — replace guessed library URLs with real cdnjs URLs
        if (filename.endsWith('.html')) {
          filecontent = resolveCDNs(filecontent);
        }

        const safePath = filename.replace(/\.\./g, '').replace(/[^a-zA-Z0-9.\-_/]/g, '-');
        const fullPath = path.join(live.workspaceDir, safePath);
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        // Cycles 2+: merge content into existing files
        const isBuilder = agentId === 'builder';
        const isUpdate  = (live.cycle || 1) > 1 && isBuilder && fs.existsSync(fullPath);
        const isFixCycle = (live.featurePriority || '').trim().startsWith('FIX:');

        // HTML: inject new sections before </body>
        if (isUpdate && safePath.startsWith('public/') && safePath.endsWith('.html') && !isFixCycle) {
          const existing = fs.readFileSync(fullPath, 'utf8');
          filecontent = existing.includes('</body>')
            ? existing.replace(/<\/body>/i, '\n' + filecontent + '\n</body>')
            : existing + '\n' + filecontent;
        }
        // CSS: append new rules — coexistence and override are safe for stylesheets
        if (isUpdate && safePath === 'public/style.css' && !isFixCycle) {
          const existingCss = fs.readFileSync(fullPath, 'utf8');
          filecontent = existingCss + '\n\n' + filecontent;
        }
        // app.js / data.js: always full replacement — builder outputs complete files each cycle.
        // No append = no const redeclaration, no state model freeze, no growing bloat.

        fs.writeFileSync(fullPath, filecontent, 'utf8');
        const lines = filecontent.split('\n').length;
        const entry = { path: safePath, content: filecontent, agentId, ts: Date.now(), lines };
        const idx = live.files.findIndex(f => f.path === safePath);
        if (idx >= 0) live.files[idx] = entry; else live.files.push(entry);
        if (agentId === 'sales') live.salesV++;
        if (safePath === 'docs/feature-priority.md') {
          // CEO sometimes outputs verbose markdown instead of one line.
          // Extract just the operational decision line (FIX:/NEW PAGE:/SECTION:)
          // so that isFix detection, pastPriorities, and lastPriority all work correctly.
          const decisionMatch = filecontent.match(/^(FIX:|NEW PAGE:|SECTION:).+/m);
          if (decisionMatch) filecontent = decisionMatch[0].trim();
          live.pastPriorities.push(filecontent.slice(0, 120));
          live.featurePriority = filecontent.trim();
        }
        emit('new-file', entry);
        if (safePath.startsWith('public/')) emit('preview-refresh', { path: safePath, ts: Date.now() });
        pushMsg({ from: agentId, to: null, type: 'file',
          message: `📄 \`${safePath}\` — ${lines} lines · ${task}` });
        pushContext(agentId, agentId, `produced ${safePath}: ${task}`);
        didWork = true;
      }
    }

    // Clear console errors after builder runs — they've been addressed this cycle
    if (agentId === 'builder' && live.consoleErrors?.length) {
      live.consoleErrors = [];
    }

    // Cycle 1: run CSS Specialist to generate pixel-perfect CSS from actual HTML.
    // The builder writes HTML and CSS in the same pass — CSS always gets less attention.
    // The specialist gets its own dedicated 10K-token call focused purely on styling.
    if (agentId === 'builder' && live.cycle === 1 && didWork) {
      await runCSSSpecialist();
    }

    // Update feature inventory after every builder run so the next cycle knows
    // exactly which functions and state keys to preserve in its full rewrite.
    if (agentId === 'builder' && didWork) {
      updateFeaturesJson();
    }

    if (!didWork) {
      const talkTo  = raw.match(/^TALKTO\s*:\s*(.+)/im)?.[1]?.trim();
      const message = raw.match(/^MESSAGE\s*:\s*(.+)/im)?.[1]?.trim() || raw.slice(0, 120);
      if (talkTo && message) {
        pushContext(talkTo, agent.name, message);
        pushMsg({ from: agentId, to: talkTo, type: 'communicate', message });
        emit('agent-status', { agentId, status: 'talking' });
      } else if (agentId === 'builder') {
        pushMsg({ from: 'system', to: null, type: 'system',
          message: `⚠️ DEVELOPER produced no files (wrote explanation/tutorial instead of code). Retrying with format correction...` });
        // Builder ignored the file format — likely wrote a markdown tutorial instead.
        // Send a strict correction prompt to extract actual files.
        try {
          const { text: corrected, inputTokens: ci3, outputTokens: co3 } = await createMessage({
            provider, apiKey, model, maxTokens: 10000,
            messages: [
              { role: 'user', content: typeof userContent === 'string' ? userContent : (userContent[userContent.length - 1]?.text || '') },
              { role: 'assistant', content: raw },
              { role: 'user', content: `You wrote an explanation/tutorial instead of code files. Output the ACTUAL CODE FILES now using ONLY this format — no markdown, no explanation, no npm commands, no TypeScript, no React:\n\nTYPE: work\nFILENAME: public/index.html\nTASK: html\n---\n[complete HTML here]\n\n===FILE===\nTYPE: work\nFILENAME: public/data.js\nTASK: data\n---\n[complete vanilla JS here]\n\n===FILE===\nTYPE: work\nFILENAME: public/app.js\nTASK: app\n---\n[complete vanilla JS here]\n\n===FILE===\nTYPE: work\nFILENAME: public/style.css\nTASK: css\n---\n[complete CSS here]` },
            ],
          });
          live.tokens += ci3 + co3;
          emit('token-update', { total: live.tokens, delta: ci3 + co3 });
          // Re-parse corrected output
          const correctedBlocks = corrected.split(/\n?={3,}FILE={3,}\n?/i);
          for (const block of correctedBlocks) {
            const typeM2 = block.match(/^TYPE\s*:\s*(\w+)/im);
            if (typeM2?.[1]?.toLowerCase() !== 'work') continue;
            const fname = block.match(/^FILENAME\s*:\s*(.+)/im)?.[1]?.trim();
            const sepM2 = block.match(/\n-{3,}\r?\n/);
            let fc = sepM2 ? block.slice(block.indexOf(sepM2[0]) + sepM2[0].length).trim() : '';
            if (!fname || !fc) continue;
            if (fname.endsWith('.js')) {
              const { valid, error } = validateJS(fc);
              if (!valid) { fc = (await retryBuilderFile({ provider, apiKey, model, brokenCode: fc, error, filename: fname, context: live.brief })) || fc; }
            }
            if (fname.endsWith('.html')) fc = resolveCDNs(fc);
            const sp = fname.replace(/\.\./g, '').replace(/[^a-zA-Z0-9.\-_/]/g, '-');
            const fp = require('path').join(live.workspaceDir, sp);
            require('fs').mkdirSync(require('path').dirname(fp), { recursive: true });
            require('fs').writeFileSync(fp, fc, 'utf8');
            const lines2 = fc.split('\n').length;
            const entry2 = { path: sp, content: fc, agentId, ts: Date.now(), lines: lines2 };
            const idx2 = live.files.findIndex(f => f.path === sp);
            if (idx2 >= 0) live.files[idx2] = entry2; else live.files.push(entry2);
            emit('new-file', entry2);
            if (sp.startsWith('public/')) emit('preview-refresh', { path: sp, ts: Date.now() });
            pushMsg({ from: agentId, to: null, type: 'file', message: `📄 \`${sp}\` — ${lines2} lines · retry` });
          }
        } catch (retryErr) {
          pushMsg({ from: 'system', to: null, type: 'system', message: `⚠️ Retry also failed: ${retryErr.message?.slice(0, 80)}` });
        }
      }
    }
  } catch (err) {
    const maxRetries = agentId === 'builder' ? 2 : 1;
    if (isConnectionError(err) && _retries < maxRetries) {
      const wait = ((_retries + 1) * 5000);
      pushMsg({ from: 'system', to: null, type: 'system',
        message: `⚠️ ${LIVE_AGENTS[agentId]?.name || agentId} connection error — retry ${_retries + 1}/${maxRetries} in ${wait / 1000}s` });
      await sleep(wait);
      return callAgent(agentId, _retries + 1);
    }
    console.error(`[${agentId}]`, err.message);
    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚠️ ${LIVE_AGENTS[agentId]?.name || agentId} error: ${err.message.slice(0, 120)}` });
  }

  emit('agent-status', { agentId, status: 'idle' });
}

async function runPipeline() {
  if (!live.running) return;
  live.cycle = (live.cycle || 0) + 1;
  const cycle = live.cycle;

  live.featurePriority = '';  // reset so previous cycle's FIX doesn't bleed in

  // Heal any JS files that got corrupted in the previous cycle before the builder rewrites them
  if (cycle > 1) await ensureValidJS();

  pushMsg({ from: 'system', to: null, type: 'system',
    message: `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━` });
  pushMsg({ from: 'system', to: null, type: 'system',
    message: `🔄 CYCLE ${cycle} — PLANNING...` });

  async function runStep(agentId) {
    while (live.paused) await sleep(500);
    if (!live.running) return;
    const name = LIVE_AGENTS[agentId]?.name.toUpperCase() || agentId;
    pushMsg({ from: 'system', to: null, type: 'system', message: `⚙️ ${name} planning...` });
    await callAgent(agentId);
  }

  // Fast-path: if customer feedback is waiting, skip planning and go straight to builder
  const isFastFeedback = !!(live.customerFeedback && live._feedbackPending);

  if (isFastFeedback) {
    pushMsg({ from: 'system', to: null, type: 'system',
      message: `⚡ CUSTOMER FEEDBACK — skipping planning, builder acting immediately` });
    while (live.paused) await sleep(500);
    await callAgent('builder');
    if (!live.running) return;
    live.customerFeedback = '';
    live._feedbackPending = false;
  } else {
    // Request a fresh screenshot from the browser and wait up to 6s before CEO runs
    live.previewScreenshot = null;  // clear stale screenshot
    emit('screenshot-request', {});
    pushMsg({ from: 'system', to: null, type: 'system', message: `📸 CEO reviewing site screenshot...` });
    for (let i = 0; i < 12; i++) {
      if (live.previewScreenshot) break;
      await sleep(500);
    }

    await runStep('ceo');
    if (!live.running) return;

    pushMsg({ from: 'system', to: null, type: 'system', message: `⚙️ LEAD ENG + DESIGNER planning in parallel...` });
    await Promise.all([callAgent('lead-eng'), callAgent('designer')]);
    if (!live.running) return;

    while (live.paused) await sleep(500);
    pushMsg({ from: 'system', to: null, type: 'system', message: `⚙️ CYCLE ${cycle} · DEVELOPER building...` });
    await callAgent('builder');
    if (!live.running) return;
    live.customerFeedback = '';  // consumed — full cycle addressed it
    live._feedbackPending = false;
  }

  // Safety net: auto-generate any required files the builder missed
  await ensureRequiredFiles();

  // CSS coverage check: if style.css doesn't cover HTML selectors, auto-patch it
  await ensureCSSCoverage();

  if (live.agents?.includes('qa')) {
    await runStep('qa');
  }

  // If new feedback arrived mid-cycle, skip the gap and act immediately
  const gap = live._feedbackPending ? 0 : Math.round(10000 / live.speed);
  const msg = live._feedbackPending
    ? `✅ CYCLE ${cycle} COMPLETE — feedback detected, acting immediately`
    : `✅ CYCLE ${cycle} COMPLETE — next round in 10s`;
  pushMsg({ from: 'system', to: null, type: 'system', message: msg });

  live.timers['pipeline'] = setTimeout(runPipeline, gap);
}

function scheduleSide(agentId) {
  if (!live.running) return;
  const delay = Math.round(LIVE_AGENTS[agentId].interval / live.speed);
  live.timers[agentId] = setTimeout(async () => {
    while (live.paused) await sleep(500);
    if (live.running) { await callAgent(agentId); scheduleSide(agentId); }
  }, delay);
}

function addClient(res) {
  live.clients.push(res);
  if (live._autoPaused) {
    live._autoPaused = false;
    live.paused = false;
    pushMsg({ from: 'system', to: null, type: 'system', message: '▶ CLIENT RECONNECTED — RESUMING' });
  }
}

function removeClient(res) {
  live.clients = live.clients.filter(c => c !== res);
  if (live.clients.length === 0 && live.running && !live.paused) {
    live.paused = true;
    live._autoPaused = true;
    console.log('[pipeline] no clients — auto-paused');
  }
}

module.exports = {
  get live() { return live; },
  setLive(s) {
    // Mutate in-place so server.js's destructured `live` reference stays valid
    Object.keys(live).forEach(k => delete live[k]);
    Object.assign(live, s);
  },
  LIVE_AGENTS,
  sleep,
  emit,
  pushContext,
  pushMsg,
  stopAll,
  callAgent,
  runPipeline,
  scheduleSide,
  addClient,
  removeClient,
};
